### ISSUE TITLE
NOT COMPATIBLE WITH PYTHON3

### ISSUE THREAD

**Issue by manishshettym** [ninjiangstar/wav-splitter-api#2]
The given code is not compatible with python3 and on changing the syntax the following error was prompted:
Traceback (most recent call last):
  File "split.py", line 13, in <module>
    ex1 = writewave(dest + '1-', splitted)
  File "/home/manish/highlight/app/utils/splitterkit.py", line 28, in writewave
    write.writeframes(data[i].data)
  File "/usr/lib/python3.5/wave.py", line 427, in writeframes
    self.writeframesraw(data)
  File "/usr/lib/python3.5/wave.py", line 415, in writeframesraw
    data = memoryview(data).cast('B')
TypeError: memoryview: a bytes-like object is required, not 'str'
Exception ignored in: <bound method Wave_write.__del__ of <wave.Wave_write object at 0x7f10724ab4e0>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/wave.py", line 316, in __del__
    self.close()
  File "/usr/lib/python3.5/wave.py", line 434, in close
    self._ensure_header_written(0)
  File "/usr/lib/python3.5/wave.py", line 457, in _ensure_header_written
    self._write_header(datasize)
  File "/usr/lib/python3.5/wave.py", line 474, in _write_header
    self._sampwidth * 8, b'data'))
struct.error: required argument is not an integer

**Comment by Kimmoteemu** [comment]
I was able to fix that problem with one line in write wave. This is now python 3 compatible ( only fixed splitting & saving)
`# Authored by Andrew Jiang
# BCG digital Ventures
import os, wave, math, collections

# define named tuples
metatuple = collections.namedtuple('metatuple', ['nchannels', 'sampwidth', 'framerate', 'nframes', 'comptype', 'compname'])
datatuple = collections.namedtuple('datatuple', ['meta', 'data'])

# opens a wav file and returns the data as a tuple
def readwave(src):
    read = wave.open(src, 'rb')
    meta = read.getparams()
    # turn params into a metatuple
    meta = metatuple(meta[0], meta[1], meta[2], meta[3], meta[4], meta[5])
    data = read.readframes(meta.nframes)
    read.close()
    return datatuple(meta, [data])

# writes to a directory
def writewave(dest, data):
    files = []
    data = separate(data)
    for i in range(len(data)):
        destfile = dest + str(i)+ '.wav'
        makedir(destfile) # make sure dir exists
        write = wave.open(destfile, 'wb')
        write.setparams(data[i].meta)
        write._nframes=int(write._nframes)
        write.writeframes(data[i].data)
        write.close()
        files.append(destfile)
    return files

# helper function that creates dir if it doesn't exist
def makedir(dest):
    if(os.path.isdir(os.path.dirname(dest)) != True):
        os.makedirs(os.path.dirname(dest))

# slices audio data at given start, end: frame#
def slicewave(data, start, end):
    if(len(data.data) > 1):
        data = merge(data) # insurance
    meta = data.meta
    start *= meta.sampwidth # deal with sample width
    end *= meta.sampwidth
    spliced = data.data[0][start:end]
    nf = len(spliced) / meta.sampwidth
    meta = meta._replace(nframes=nf)
    return datatuple(meta, [spliced])

# slices audio data at given start, end: seconds
def slicewave_s(data, start, end):
    fr = float(data.meta.framerate)
    newdata = slicewave(data, int(float(start) * fr), int(float(end) * fr))
    return newdata

# splits audio data into equal intervals: # of frames
def split(data, interval=None, overlap=None):
    if(interval == None):
        interval = data.meta.framerate # =1s
    if(overlap == None):
        overlap = interval
    if(interval < 1 or overlap < 1):
        raise ValueError('cannot iterate')
    iterations = int(math.ceil(1.0 * data.meta.nframes / interval))
    canned = []
    for i in range(iterations):
        start = i * interval
        end = start + overlap
        canned.append(slicewave(data, start, end))
    newdata = combine(canned)
    return newdata

# splits audio data into equal intervals: seconds
def split_s(data, interval=None, overlap=None):
    fr = float(data.meta.framerate)
    if(interval != None):
        interval = int(float(interval) * fr)
    if(overlap != None):
        overlap = int(float(overlap) * fr)
    newdata = split(data, interval, overlap)
    return newdata

# separate a data tuple containing multiple audio tracks
# into an array of data tuples containing single audio tracks
def separate(data):
    newdata = []
    nframes = data.meta.nframes
    ndata = len(data.data)
    for i in range(ndata):
        nf = len(data.data[i]) / data.meta.sampwidth
        meta = data.meta._replace(nframes=nf)
        newdata.append(datatuple(meta, data.data[i]))
    return newdata

# combine an array of data tuples containing single audio tracks
# into a single data tuple containing multiple audio tracks
def combine(data):
    newdata = []
    meta = data[0].meta
    for i in range(len(data)):
        newdata += data[i].data
    nf = len(b''.join(newdata)) / meta.sampwidth
    meta = meta._replace(nframes=nf)
    return datatuple(meta, newdata)

# merge multiple audio tracks into one
def merge(data):
    meta = data.meta
    newdata = ''.join(data.data)
    return datatuple(meta, [newdata])
`

**Comment by manishshettym** [comment]
:+1:
